name: Test Project Backend

on:
  push:
    branches: feature/project-template
  pull_request:
    branches: feature/project-template

defaults:
  run:
    working-directory: TownLibrary-Backend

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: ci
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with gradle
      run: ./gradlew build -x test
    - name: Run persistence tests
      run: ./gradlew persistenceTest
    - name: Run unit tests
      run: ./gradlew unitTest
    - name: Run integration tests
      run: ./gradlew integrationTest
    - name: Code coverage check
      run: ./gradlew jacocoLogUnitTestCoverage | awk '/Instruction Coverage:/ { exit(substr($4, 0, length($4) - 1) >= 90.0) }'
