name: Deploy Project Backend

on:
  workflow_run:
    workflows: ['Test Project Backend']
    branches: [main]
    types:
      - completed

defaults:
  run:
    working-directory: TownLibrary-Backend

jobs:
  deploy-to-heroku:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12   # plugin for automated heroku deploy
      with:
        heroku_api_key: '6c6171f4-6dd1-49c7-bc0d-d25a94f39eee'
        heroku_app_name: 'townlibrary-backend-321f21-g11'
        heroku_email: 'yuan-po.teng@mail.mcgill.ca'
