name: Test Project Backend

on:
  push:
  pull_request:
    branches: feature/project-template

defaults:
  run:
    working-directory: TownLibrary-Backend

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: ci
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with gradle
      run: ./gradlew build -xtest
    - name: Run unit test
      run: ./gradlew unitTest
    - name: Run integration test
      run: ./gradlew integrationTest
    - name: Check code coverage
      run: |
        ./gradlew jacocoLogUnitTestCoverage | awk '/Complexity Coverage:/ { exit !($4 >= 65.0) }'
        ./gradlew jacocoLogIntegrationTestCoverage | awk '/Instruction Coverage:/ { exit !($4 >= 65.0) }'
