name: Workflow for Project Backend

on:
  push:
    branches: main
  pull_request:
    branches: main

defaults:
  run:
    working-directory: TownLibrary-Backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Buld with gradle
      run: ./gradlew build
    - uses: akhileshns/heroku-deploy@v3.12.12   # plugin for automated heroku deploy
      with:
        heroku_api_key: '6c6171f4-6dd1-49c7-bc0d-d25a94f39eee'
        heroku_app_name: 'townlibrary-backend-321f21-g11'
        heroku_email: 'yuan-po.teng@mail.mcgill.ca'
