name: Workflow for Project Backend

on:
  push:
    branches: main
  pull_request:
    branches: main

defaults:
  run:
    working-directory: TownLibrary-Backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Buld with gradle
      run: ./gradlew build

