name: Test Project Vue App

on:
  push:
  pull_request:
    branches: feature/project-template

defaults:
  run:
    working-directory: TownLibrary-Frontend

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: ci
    steps:
    - uses: actions/checkout@v2
    - name: Set up nodejs 12
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Upgrade npm
      run: npm install -g npm@latest  # make sure we are on at least npm 7
    - name: Install dependencies
      run: npm ci
    - name: Build with npm
      run: npm run build
    - name: Make sure unit tests are not broken
      run: npm run unit